id: c320d4713e13446f9b2f38d1b1021a90
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_514-Discourse_of_Dh%C4%81ra%E1%B9%87%C4%AB_of_Buddha%E2%80%99s_Essence-v2
  language: en
  author: ''
  volume: {}
